# Model
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 16
split: [0.75, 0.25]
seed: 0

# Train
epochs: 10
batch_size: 16
batch_number: 2
lr: 0.001

# Log
log_every: 5
log_last: 1
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
