# Model
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 16
split: [0.75, 0.25]
seed: 0

# Train
epochs: 20
batch_size: 32
batch_number: 1
lr: 0.001

# Log
log_every: 10
log_last: 10
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
