# Model
hidden_size: 128
pos_enc: False

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 8
split: [0.8, 0.1, 0.1]
seed: 0

# Train
epochs: 1
batch_size: 32
lr: 0.001

# Log
log_every: 50
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
