# Model
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 16
seq_len: 8
split: [0.75, 0.25]
seed: 0

# Train
epochs: 50
batch_size: 4
batch_number: 8
lr: 0.001
wd: 0.01

# Log
log_every: 50
log_last: 90
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
