# Model
hidden_size: 128
pos_enc: False

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 32
split: [0.75, 0.25]
seed: 9

# Train
epochs: 100
batch_size: 16
lr: 0.001

# Log
log_every: 100
log_last: 10
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
