# Model
hidden_size: 256

# Dataset
dataset: mcords3
patch_len: 32
seq_len: 16
split: [0.75, 0.25]
seed: 1

# Train
epochs: 50
batch_size: 2
batch_number: 16
lr: 0.0001
wd: 0.001

# Log
log_every: 1
log_last: 40
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
