# Bash
train_script: train
script_dir: /home/jordydalcorso/workspace/recurrent-sounder/scripts
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
container_name: rec_jordydalcorso

# Model
model: u
hidden_size: 1024
pos_enc: False

# Dataset
dataset: mcords3
patch_len: 64
seq_len: 2
split: [0.6, 0.2, 0.2]
first_only: False
seed: 10

# Train
epochs: 500
batch_size: 2
lr: 0.0001

# Log
log_every: 50
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info