# Model
n_trials: 2
train_func: cycle
model: nlur
hidden_size: 256

# Dataset
dataset: mcords3
patch_len: 32
seq_len: 4
chunk_len: 16
split: [0.75, 0.25]
first_only: False
data_aug: False
seed: 0

# Train
epochs: 1
batch_size: 4
batch_number: 16
lr: [0.0001, 0.01]
wd: [0.0001, 0.1]

# Log
log_every: 100
log_last: 400
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
