# Model
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 100
seed: 0
split: [0.8, 0.1, 0.1]

# Qualitative
batch_size: 3
font_size: 14
aspect: 4

# Log
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
