# Model
hidden_size: 128
n_classes: 4
pos_enc: False

# Dataset
data_dir: /home/jordydalcorso/workspace/datasets/MCORDS1/
patch_len: 1
seq_len: 2000
seed: 0
split: [0.8, 0.1, 0.1]

# Qualitative
batch_size: 3
font_size: 17
aspect: 3

# Log
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
