# Model
model: nlur
hidden_size: 128
pos_enc: False

# Dataset
dataset: mcords3
patch_len: 32
seq_len: 128
split: [0.75, 0.25]
first_only: False
seed: 0

# Test
batch_size: 1

# Log
return_dict: False
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
