# Model
model: u
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 128
split: [0.75, 0.25]
first_only: True
seed: 9

# Test
batch_size: 16

# Log
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
