# Model
model: u
hidden_size: 128
pos_enc: False

# Dataset
dataset: mcords3
patch_len: 64
seq_len: 2
split: [0.6, 0.2, 0.2]
first_only: False
seed: 9

# Test
batch_size: 1

# Log
return_dict: False
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
