# Model
model: nlur
hidden_size: 128
pos_enc: False

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 16
split: [0.8, 0.1, 0.1]
seed: 0

# Test
batch_size: 64

# Log
return_dict: False
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
