# Model
model: nlur
hidden_size: 128

# Dataset
dataset: mcords1
patch_len: 32
seq_len: 16
split: [0.75, 0.25]
seed: 9

# Test
batch_size: 32

# Log
return_dict: True
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
