hidden_size: 64
patch_len: 16
seq_len: 10
test_size: 0.1
epochs: 1
batch_size: 8
lr: 0.001
data_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_rg.pt
label_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_sg5.pt
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
