# Model
hidden_size: 128
hidden_scaling: 2
n_layers: 4
n_classes: 5

# Dataset
data_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_rg.pt
label_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_sg5.pt
patch_len: 16
seq_len: 10
test_size: 0.1

# Train
epochs: 3
batch_size: 8
lr: 0.001

# Log
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
