hidden_size: 64
patch_len: 32
seq_len: 8
test_size: 0.1
epochs: 50
batch_size: 64
lr: 0.001
data_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_rg.pt
label_dir: /home/jordydalcorso/workspace/datasets/SHARAD/sharad_north_sg5.pt
out_dir: /home/jordydalcorso/workspace/sequential/output
log_dir: /home/jordydalcorso/workspace/sequential/output
log_level: info
