# Model
model: nlur
hidden_size: 256
pos_enc: False

# Dataset
dataset: mcords3
patch_len: 32
seq_len: 32
chunk_len: 16
split: [0.75, 0.25]
first_only: False
data_aug: False
seed: 0

# Train
epochs: 1000
batch_size: 8
lr: 0.0001

# Log
log_every: 50
log_last: 400
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
