# Model
model: nlur
hidden_size: 128
n_classes: 5
pos_enc: False

# Dataset
data_dir: /home/jordydalcorso/workspace/datasets/MCORDS3_Miguel/tif
patch_len: 32
seq_len: 16
split: [0.8, 0.1, 0.1]
seed: 0

# Train
epochs: 10
batch_size: 8
lr: 0.001
ce_weights: [0.0545, 0.0363, 0.7131, 0.0588, 0.1374]

# Log
log_every: 10
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
