# Model
model: 'urnet'
hidden_size: 128
hidden_scaling: 1
kernel_size: 5
n_layers: 3
n_classes: 4
pos_enc: True

# Dataset
data_dir: /home/jordydalcorso/workspace/datasets/MCORDS1_Ilisei/rg_MCORDS1.pt #SHARAD/sharad_north_rg.pt
label_dir: /home/jordydalcorso/workspace/datasets/MCORDS1_Ilisei/sg_MCORDS1.pt #SHARAD/sharad_north_sg5.pt
patch_len: 32
seq_len: 20
test_size: 0.1

# Train
epochs: 5
batch_size: 8
lr: 0.001

# Log
out_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_dir: /home/jordydalcorso/workspace/recurrent-sounder/log
log_level: info
